title: CuraEngine developer portal
description: Development documentation and Benchmark results for CuraEngine
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://ultimaker.github.io/CuraEngine

aux_links:
    Repository: https://github.com/Ultimaker/CuraEngine
    Benchmarks: https://ultimaker.github.io/CuraEngine/dev/bench/